ENT.Base 			= "npc_vj_l4d_com_female_l4d2"
ENT.Type 			= "ai"
ENT.PrintName 		= "Common Infected (Female Swamp)"
ENT.Author 			= "Darkborn"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Purpose 		= "Spawn it and fight with it!"
ENT.Instructions 	= "Click on the spawnicon to spawn it."
ENT.Category		= "Left 4 Dead 2"